### PR TITLE
fix: Prevent org-roam from failing to be referenced in other files.

### PR DESCRIPTION
**Pull request by ISouthRain**
When the org-roam file is referenced in other files, if the id is changed, the reference will fail and the source cannot be found. This fixes the problem.

### CODE REVIEW

**Comment by yibie** [comment]
Hello, I’d like to know why this issue occurs. Under what circumstances would the ID generated by org-roam change? I’ve been using org-roam for a long time and haven’t encountered this situation before.

**Comment by ISouthRain** [comment]
https://github.com/user-attachments/assets/6390e0fc-14ed-4391-88fb-4400eaedd34e

If the roam ID changes, the source will not be found in other files.

**Comment by yibie** [comment]
Yes. But what make the org-roam id changed? Like me, I used org-roam for two years. I knew org-roam located the file by ids, so I won't changed the id at all. 

I'm not arguing with you, just want to clearly about the problem. And this is very important, because org-zettel-ref-mode locate the  files by file-name, and if this is a problem must be fix, that will change the package logic inside.

**Comment by yibie** [comment]
I saw that you run =M-x org-roam-db-sync=, then the id for the note changed. I don't get it, beacuse I also used this function often, but it never changed the id of my notes. 

Ok, it may be I found the really problem is, the overview notes didn't saved on the disk, so when you run the function, the id of the note would changed. 

Let me see, and give me some time.

**Comment by ISouthRain** [comment]
On:
```
(defun org-zettel-ref-generate-org-roam-content (title)
  "Generate org-roam compatible file content with TITLE."
  (let ((id (org-id-new)))
    (format "#+title: %s\n#+roam_tags:\n\n* %s\n:PROPERTIES:\n:ID:       %s\n:END:\n\n"
            title title id)))
```
ID From: org-id-new 
Fix link: 
https://github.com/yibie/org-zettel-ref-mode/compare/master...ISouthRain:org-zettel-ref-mode:ref-roam-id#diff-b8a06e0b16e6685e4d8ce5982f119b25362fbfd1c4bdec2bc5d7e50eaab9fffbR92

I fixed the problem, and I did ensure that the ID would not change, but it introduced a new problem.
If org-zettel creates a new file, it will reuse the ID of the previous org-zettel.

I know what's causing this, it's because the org-zettel-ref-overview-file in the PR hasn't been updated yet...

It's because org-zettel-ref-generate-org-roam-content is referenced earlier than org-zettel-ref-overview-file

**Comment by yibie** [comment]
I greatly appreciate your participation and PR, but I still recommend that you file an issue and fully explain the problem you encountered. I don’t accept direct code merges unless the issue has been thoroughly discussed. Otherwise, the side effects of the code could cause significant problems.

**Comment by ISouthRain** [comment]
不要担心, 我已经取消了 PR, 这是一个测试过程
动画1

**Pull request closed without merging**
